import { NextApiRequest, NextApiResponse } from 'next';
export default (req: NextApiRequest, res: NextApiResponse) => {
  res.statusCode = 200;
  res.json(
    [
      {
        _id: 1,
        isLike: false,
        rate: 4,
        avatar: '/sellers/avatars/1.png',
        name: 'Antonio',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 2,
        isLike: false,
        rate: 5,
        avatar: '/sellers/avatars/2.png',
        name: 'Antonio',
        location: 'Málaga, España',
        followingCount: 260,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 3,
        isLike: false,
        rate: 1,
        avatar: '/sellers/avatars/3.png',
        name: 'Antonio',
        location: 'Pesaro, Italia',
        followingCount: 195,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 1,
        isLike: false,
        rate: 4,
        avatar: '/sellers/avatars/4.png',
        name: 'Antonio',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 5,
        isLike: false,
        rate: 4,
        avatar: '/sellers/avatars/5.png',
        name: 'Antonio',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 6,
        isLike: false,
        rate: 3,
        avatar: '/sellers/avatars/6.png',
        name: 'Mejillones | Mariscos',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 7,
        isLike: false,
        rate: 2,
        avatar: '/sellers/avatars/7.png',
        name: 'Mejillones | Mariscos',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 8,
        isLike: false,
        rate: 4,
        avatar: '/sellers/avatars/8.png',
        name: 'Mejillones | Mariscos',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 9,
        isLike: false,
        rate: 4,
        avatar: '/sellers/avatars/9.png',
        name: 'Mejillones | Mariscos',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 10,
        isLike: false,
        rate: 4,
        avatar: '/sellers/avatars/10.png',
        name: 'Mejillones | Mariscos',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 11,
        isLike: false,
        rate: 4,
        avatar: '/sellers/avatars/11.png',
        name: 'Mejillones | Mariscos',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      },
      {
        _id: 12,
        isLike: false,
        rate: 4,
        avatar: '/sellers/avatars/12.png',
        name: 'Mejillones | Mariscos',
        location: 'Málaga, España',
        followingCount: 340,
        description: 'Somos una pescadería malagueña que comercializa pescado fresco desde 1976, tenemos el placer de estar presentes de forma...',
      }
    ]
  )
}